In [2]:
%tensorflow_version 2.x
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

TensorFlow 2.x selected.


In [3]:
tf.__version__     # check tesor flow version

'2.1.0'

In [0]:
!pip install tensorflow --upgrade # if not the latest, update it

     |████████████████████████████████| 86.3MB 48.3MB/s 
     |████████████████████████████████| 450kB 43.4MB/s 
     |████████████████████████████████| 3.8MB 29.8MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0rc3
    Uninstalling tensorflow-1.15.0rc3:
      Successfully uninstalled tensorflow-1.15.0rc3


In [0]:
tfds.list_builders() # check for the avilable datasets inside tensor_flow

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'arc',
 'bair_robot_pushing_small',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'cos_e',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'dmlab',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'duke_ultrasound',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'esnli',
 'eurosat',
 'fashion_mnist',
 'flic',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'groove',
 'higgs',
 'horses_or_humans',
 'i_natura

In [5]:
(train_data, validation_data, test_data), metadata = tfds.load(
'imdb_reviews',
split=['train[:80%]', 'train[80%:90%]', 'train[20%:]'],
with_info=True,
as_supervised=True,)  # create 03 datasets, for training, testing and validation - Training - 80% from total dataset, Testing - remaining 20% from the total dataset,  validation, 90% from the quotq of 80% allocated for training

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteOGM5UP/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteOGM5UP/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteOGM5UP/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [6]:
train_data

<DatasetV1Adapter shapes: ((), ()), types: (tf.string, tf.int64)>

In [18]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(2))) #read  10 user-reviews. You need to iterate in reading those, cannot be read directly.
train_examples_batch

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [15]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [0]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(pretrained_model, input_shape=[], dtype=tf.string, trainable=True)  # pre-trained neural network to convert encode text reviews to numerical vectors

In [17]:
hub_layer(train_examples_batch[:2]) # encoded view of the frist two review feedbacks

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ]],
      dtype=float32)>

In [0]:
train_examples_batch[:2]

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [0]:
model = tf.keras.Sequential()
model.add(hub_layer) # input layer is the encoded output from tensor_flow hub neural networ
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer_1 (KerasLayer)   (None, 20)                400020    
_________________________________________________________________
dense_2 (Dense)              (None, 16)                336       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])  # back_prop configuration

In [0]:
model.fit(train_data.shuffle(10000).batch(512),
         epochs=20,
         validation_data=validation_data.batch(512),
         verbose=1) #get ready maximum buffer or 10000 record for training purpose and shuffle them to avoid overfitting. After, feed block sizes of 512 (to prevent RAM memory overflow)for training purposes from the suffled content. verbose will define the o/p results taking place in training phase.
                    # usually, batch sizes are defined as series of 32, 64,128, 256, 512.... More it become big, model maturity is high, but should be managiable to computer HW and shiuld be smaller than the total dataset size

Epoch 1/20
40/40 [==============================] - 5s 137ms/step - loss: 1.0493 - accuracy: 0.4611 - val_loss: 0.7646 - val_accuracy: 0.4552
Epoch 2/20
40/40 [==============================] - 5s 127ms/step - loss: 0.7333 - accuracy: 0.5112 - val_loss: 0.7004 - val_accuracy: 0.5540
Epoch 3/20
40/40 [==============================] - 5s 132ms/step - loss: 0.6745 - accuracy: 0.5939 - val_loss: 0.6488 - val_accuracy: 0.6272
Epoch 4/20
40/40 [==============================] - 5s 137ms/step - loss: 0.6308 - accuracy: 0.6482 - val_loss: 0.6085 - val_accuracy: 0.6804
Epoch 5/20
40/40 [==============================] - 5s 137ms/step - loss: 0.5901 - accuracy: 0.6899 - val_loss: 0.5716 - val_accuracy: 0.7192
Epoch 6/20
40/40 [==============================] - 6s 141ms/step - loss: 0.5538 - accuracy: 0.7293 - val_loss: 0.5347 - val_accuracy: 0.7576
Epoch 7/20
40/40 [==============================] - 6s 138ms/step - loss: 0.5098 - accuracy: 0.7652 - val_loss: 0.4969 - val_accuracy: 0.7856
Epoch 

In [0]:
model.predict(["This is the worst movie I have ever seen",
              "An excellent movie that I enjoyed a lot",
              "how can one make such a horrible movie? there is no story, acting direction everything is very poor"])

array([[0.12370643],
       [0.9905675 ],
       [0.01358755]], dtype=float32)

In [0]:
model.predict(["An excellent movie that I enjoyed a lot"])

array([[0.9905675]], dtype=float32)